#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CINEMA")]
	public partial class CinemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertQuocGia(QuocGia instance);
    partial void UpdateQuocGia(QuocGia instance);
    partial void DeleteQuocGia(QuocGia instance);
    partial void InsertPhim(Phim instance);
    partial void UpdatePhim(Phim instance);
    partial void DeletePhim(Phim instance);
    partial void InsertTheLoaiPhim(TheLoaiPhim instance);
    partial void UpdateTheLoaiPhim(TheLoaiPhim instance);
    partial void DeleteTheLoaiPhim(TheLoaiPhim instance);
    partial void InsertCaiDatSuatChieu(CaiDatSuatChieu instance);
    partial void UpdateCaiDatSuatChieu(CaiDatSuatChieu instance);
    partial void DeleteCaiDatSuatChieu(CaiDatSuatChieu instance);
    partial void InsertGhe(Ghe instance);
    partial void UpdateGhe(Ghe instance);
    partial void DeleteGhe(Ghe instance);
    partial void InsertCaiDatGhe(CaiDatGhe instance);
    partial void UpdateCaiDatGhe(CaiDatGhe instance);
    partial void DeleteCaiDatGhe(CaiDatGhe instance);
    partial void InsertPhongChieu(PhongChieu instance);
    partial void UpdatePhongChieu(PhongChieu instance);
    partial void DeletePhongChieu(PhongChieu instance);
    partial void InsertChucVuNhanVien(ChucVuNhanVien instance);
    partial void UpdateChucVuNhanVien(ChucVuNhanVien instance);
    partial void DeleteChucVuNhanVien(ChucVuNhanVien instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertSuatChieu(SuatChieu instance);
    partial void UpdateSuatChieu(SuatChieu instance);
    partial void DeleteSuatChieu(SuatChieu instance);
    #endregion
		
		public CinemaDataContext() : 
				base(global::CinemaManagementSystem.Properties.Settings.Default.CINEMAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CinemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CinemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CinemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CinemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<QuocGia> QuocGias
		{
			get
			{
				return this.GetTable<QuocGia>();
			}
		}
		
		public System.Data.Linq.Table<Phim> Phims
		{
			get
			{
				return this.GetTable<Phim>();
			}
		}
		
		public System.Data.Linq.Table<TheLoaiPhim> TheLoaiPhims
		{
			get
			{
				return this.GetTable<TheLoaiPhim>();
			}
		}
		
		public System.Data.Linq.Table<CaiDatSuatChieu> CaiDatSuatChieus
		{
			get
			{
				return this.GetTable<CaiDatSuatChieu>();
			}
		}
		
		public System.Data.Linq.Table<Ghe> Ghes
		{
			get
			{
				return this.GetTable<Ghe>();
			}
		}
		
		public System.Data.Linq.Table<CaiDatGhe> CaiDatGhes
		{
			get
			{
				return this.GetTable<CaiDatGhe>();
			}
		}
		
		public System.Data.Linq.Table<PhongChieu> PhongChieus
		{
			get
			{
				return this.GetTable<PhongChieu>();
			}
		}
		
		public System.Data.Linq.Table<ChucVuNhanVien> ChucVuNhanViens
		{
			get
			{
				return this.GetTable<ChucVuNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<SuatChieu> SuatChieus
		{
			get
			{
				return this.GetTable<SuatChieu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(255)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuocGia")]
	public partial class QuocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQuocGia;
		
		private string _TenQuocGia;
		
		private EntitySet<Phim> _Phims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuocGiaChanging(int value);
    partial void OnMaQuocGiaChanged();
    partial void OnTenQuocGiaChanging(string value);
    partial void OnTenQuocGiaChanged();
    #endregion
		
		public QuocGia()
		{
			this._Phims = new EntitySet<Phim>(new Action<Phim>(this.attach_Phims), new Action<Phim>(this.detach_Phims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuocGia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaQuocGia
		{
			get
			{
				return this._MaQuocGia;
			}
			set
			{
				if ((this._MaQuocGia != value))
				{
					this.OnMaQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaQuocGia = value;
					this.SendPropertyChanged("MaQuocGia");
					this.OnMaQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuocGia", DbType="NVarChar(255)")]
		public string TenQuocGia
		{
			get
			{
				return this._TenQuocGia;
			}
			set
			{
				if ((this._TenQuocGia != value))
				{
					this.OnTenQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._TenQuocGia = value;
					this.SendPropertyChanged("TenQuocGia");
					this.OnTenQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuocGia_Phim", Storage="_Phims", ThisKey="MaQuocGia", OtherKey="MaQuocGia")]
		public EntitySet<Phim> Phims
		{
			get
			{
				return this._Phims;
			}
			set
			{
				this._Phims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phims(Phim entity)
		{
			this.SendPropertyChanging();
			entity.QuocGia = this;
		}
		
		private void detach_Phims(Phim entity)
		{
			this.SendPropertyChanging();
			entity.QuocGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phim")]
	public partial class Phim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhim;
		
		private string _TenPhim;
		
		private System.Nullable<int> _ThoiLuong;
		
		private System.Nullable<int> _MaQuocGia;
		
		private string _MoTa;
		
		private System.Nullable<int> _NamPhatHanh;
		
		private string _DaoDien;
		
		private System.Nullable<bool> _DaXoa;
		
		private string _Poster;
		
		private System.Nullable<int> _MaTheLoaiPhim;
		
		private EntitySet<SuatChieu> _SuatChieus;
		
		private EntityRef<QuocGia> _QuocGia;
		
		private EntityRef<TheLoaiPhim> _TheLoaiPhim;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhimChanging(int value);
    partial void OnMaPhimChanged();
    partial void OnTenPhimChanging(string value);
    partial void OnTenPhimChanged();
    partial void OnThoiLuongChanging(System.Nullable<int> value);
    partial void OnThoiLuongChanged();
    partial void OnMaQuocGiaChanging(System.Nullable<int> value);
    partial void OnMaQuocGiaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnNamPhatHanhChanging(System.Nullable<int> value);
    partial void OnNamPhatHanhChanged();
    partial void OnDaoDienChanging(string value);
    partial void OnDaoDienChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnPosterChanging(string value);
    partial void OnPosterChanged();
    partial void OnMaTheLoaiPhimChanging(System.Nullable<int> value);
    partial void OnMaTheLoaiPhimChanged();
    #endregion
		
		public Phim()
		{
			this._SuatChieus = new EntitySet<SuatChieu>(new Action<SuatChieu>(this.attach_SuatChieus), new Action<SuatChieu>(this.detach_SuatChieus));
			this._QuocGia = default(EntityRef<QuocGia>);
			this._TheLoaiPhim = default(EntityRef<TheLoaiPhim>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhim", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhim
		{
			get
			{
				return this._MaPhim;
			}
			set
			{
				if ((this._MaPhim != value))
				{
					this.OnMaPhimChanging(value);
					this.SendPropertyChanging();
					this._MaPhim = value;
					this.SendPropertyChanged("MaPhim");
					this.OnMaPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhim", DbType="NVarChar(255)")]
		public string TenPhim
		{
			get
			{
				return this._TenPhim;
			}
			set
			{
				if ((this._TenPhim != value))
				{
					this.OnTenPhimChanging(value);
					this.SendPropertyChanging();
					this._TenPhim = value;
					this.SendPropertyChanged("TenPhim");
					this.OnTenPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiLuong", DbType="Int")]
		public System.Nullable<int> ThoiLuong
		{
			get
			{
				return this._ThoiLuong;
			}
			set
			{
				if ((this._ThoiLuong != value))
				{
					this.OnThoiLuongChanging(value);
					this.SendPropertyChanging();
					this._ThoiLuong = value;
					this.SendPropertyChanged("ThoiLuong");
					this.OnThoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuocGia", DbType="Int")]
		public System.Nullable<int> MaQuocGia
		{
			get
			{
				return this._MaQuocGia;
			}
			set
			{
				if ((this._MaQuocGia != value))
				{
					if (this._QuocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaQuocGia = value;
					this.SendPropertyChanged("MaQuocGia");
					this.OnMaQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(3000)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamPhatHanh", DbType="Int")]
		public System.Nullable<int> NamPhatHanh
		{
			get
			{
				return this._NamPhatHanh;
			}
			set
			{
				if ((this._NamPhatHanh != value))
				{
					this.OnNamPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._NamPhatHanh = value;
					this.SendPropertyChanged("NamPhatHanh");
					this.OnNamPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaoDien", DbType="NVarChar(255)")]
		public string DaoDien
		{
			get
			{
				return this._DaoDien;
			}
			set
			{
				if ((this._DaoDien != value))
				{
					this.OnDaoDienChanging(value);
					this.SendPropertyChanging();
					this._DaoDien = value;
					this.SendPropertyChanged("DaoDien");
					this.OnDaoDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poster", DbType="NVarChar(255)")]
		public string Poster
		{
			get
			{
				return this._Poster;
			}
			set
			{
				if ((this._Poster != value))
				{
					this.OnPosterChanging(value);
					this.SendPropertyChanging();
					this._Poster = value;
					this.SendPropertyChanged("Poster");
					this.OnPosterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTheLoaiPhim", DbType="Int")]
		public System.Nullable<int> MaTheLoaiPhim
		{
			get
			{
				return this._MaTheLoaiPhim;
			}
			set
			{
				if ((this._MaTheLoaiPhim != value))
				{
					if (this._TheLoaiPhim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTheLoaiPhimChanging(value);
					this.SendPropertyChanging();
					this._MaTheLoaiPhim = value;
					this.SendPropertyChanged("MaTheLoaiPhim");
					this.OnMaTheLoaiPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_SuatChieu", Storage="_SuatChieus", ThisKey="MaPhim", OtherKey="MaPhim")]
		public EntitySet<SuatChieu> SuatChieus
		{
			get
			{
				return this._SuatChieus;
			}
			set
			{
				this._SuatChieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuocGia_Phim", Storage="_QuocGia", ThisKey="MaQuocGia", OtherKey="MaQuocGia", IsForeignKey=true)]
		public QuocGia QuocGia
		{
			get
			{
				return this._QuocGia.Entity;
			}
			set
			{
				QuocGia previousValue = this._QuocGia.Entity;
				if (((previousValue != value) 
							|| (this._QuocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuocGia.Entity = null;
						previousValue.Phims.Remove(this);
					}
					this._QuocGia.Entity = value;
					if ((value != null))
					{
						value.Phims.Add(this);
						this._MaQuocGia = value.MaQuocGia;
					}
					else
					{
						this._MaQuocGia = default(Nullable<int>);
					}
					this.SendPropertyChanged("QuocGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoaiPhim_Phim", Storage="_TheLoaiPhim", ThisKey="MaTheLoaiPhim", OtherKey="MaTheLoaiPhim", IsForeignKey=true)]
		public TheLoaiPhim TheLoaiPhim
		{
			get
			{
				return this._TheLoaiPhim.Entity;
			}
			set
			{
				TheLoaiPhim previousValue = this._TheLoaiPhim.Entity;
				if (((previousValue != value) 
							|| (this._TheLoaiPhim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheLoaiPhim.Entity = null;
						previousValue.Phims.Remove(this);
					}
					this._TheLoaiPhim.Entity = value;
					if ((value != null))
					{
						value.Phims.Add(this);
						this._MaTheLoaiPhim = value.MaTheLoaiPhim;
					}
					else
					{
						this._MaTheLoaiPhim = default(Nullable<int>);
					}
					this.SendPropertyChanged("TheLoaiPhim");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SuatChieus(SuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phim = this;
		}
		
		private void detach_SuatChieus(SuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.Phim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheLoaiPhim")]
	public partial class TheLoaiPhim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTheLoaiPhim;
		
		private string _TenTheLoaiPhim;
		
		private EntitySet<Phim> _Phims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTheLoaiPhimChanging(int value);
    partial void OnMaTheLoaiPhimChanged();
    partial void OnTenTheLoaiPhimChanging(string value);
    partial void OnTenTheLoaiPhimChanged();
    #endregion
		
		public TheLoaiPhim()
		{
			this._Phims = new EntitySet<Phim>(new Action<Phim>(this.attach_Phims), new Action<Phim>(this.detach_Phims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTheLoaiPhim", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTheLoaiPhim
		{
			get
			{
				return this._MaTheLoaiPhim;
			}
			set
			{
				if ((this._MaTheLoaiPhim != value))
				{
					this.OnMaTheLoaiPhimChanging(value);
					this.SendPropertyChanging();
					this._MaTheLoaiPhim = value;
					this.SendPropertyChanged("MaTheLoaiPhim");
					this.OnMaTheLoaiPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTheLoaiPhim", DbType="NVarChar(255)")]
		public string TenTheLoaiPhim
		{
			get
			{
				return this._TenTheLoaiPhim;
			}
			set
			{
				if ((this._TenTheLoaiPhim != value))
				{
					this.OnTenTheLoaiPhimChanging(value);
					this.SendPropertyChanging();
					this._TenTheLoaiPhim = value;
					this.SendPropertyChanged("TenTheLoaiPhim");
					this.OnTenTheLoaiPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoaiPhim_Phim", Storage="_Phims", ThisKey="MaTheLoaiPhim", OtherKey="MaTheLoaiPhim")]
		public EntitySet<Phim> Phims
		{
			get
			{
				return this._Phims;
			}
			set
			{
				this._Phims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phims(Phim entity)
		{
			this.SendPropertyChanging();
			entity.TheLoaiPhim = this;
		}
		
		private void detach_Phims(Phim entity)
		{
			this.SendPropertyChanging();
			entity.TheLoaiPhim = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaiDatSuatChieu")]
	public partial class CaiDatSuatChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCaiDatSuatChieu;
		
		private System.Nullable<System.DateTime> _NgayChieu;
		
		private System.Nullable<int> _MaPhongChieu;
		
		private EntitySet<SuatChieu> _SuatChieus;
		
		private EntityRef<PhongChieu> _PhongChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCaiDatSuatChieuChanging(int value);
    partial void OnMaCaiDatSuatChieuChanged();
    partial void OnNgayChieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChieuChanged();
    partial void OnMaPhongChieuChanging(System.Nullable<int> value);
    partial void OnMaPhongChieuChanged();
    #endregion
		
		public CaiDatSuatChieu()
		{
			this._SuatChieus = new EntitySet<SuatChieu>(new Action<SuatChieu>(this.attach_SuatChieus), new Action<SuatChieu>(this.detach_SuatChieus));
			this._PhongChieu = default(EntityRef<PhongChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCaiDatSuatChieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCaiDatSuatChieu
		{
			get
			{
				return this._MaCaiDatSuatChieu;
			}
			set
			{
				if ((this._MaCaiDatSuatChieu != value))
				{
					this.OnMaCaiDatSuatChieuChanging(value);
					this.SendPropertyChanging();
					this._MaCaiDatSuatChieu = value;
					this.SendPropertyChanged("MaCaiDatSuatChieu");
					this.OnMaCaiDatSuatChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChieu", DbType="Date")]
		public System.Nullable<System.DateTime> NgayChieu
		{
			get
			{
				return this._NgayChieu;
			}
			set
			{
				if ((this._NgayChieu != value))
				{
					this.OnNgayChieuChanging(value);
					this.SendPropertyChanging();
					this._NgayChieu = value;
					this.SendPropertyChanged("NgayChieu");
					this.OnNgayChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongChieu", DbType="Int")]
		public System.Nullable<int> MaPhongChieu
		{
			get
			{
				return this._MaPhongChieu;
			}
			set
			{
				if ((this._MaPhongChieu != value))
				{
					if (this._PhongChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhongChieu = value;
					this.SendPropertyChanged("MaPhongChieu");
					this.OnMaPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaiDatSuatChieu_SuatChieu", Storage="_SuatChieus", ThisKey="MaCaiDatSuatChieu", OtherKey="MaCaiDatSuatChieu")]
		public EntitySet<SuatChieu> SuatChieus
		{
			get
			{
				return this._SuatChieus;
			}
			set
			{
				this._SuatChieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_CaiDatSuatChieu", Storage="_PhongChieu", ThisKey="MaPhongChieu", OtherKey="MaPhongChieu", IsForeignKey=true)]
		public PhongChieu PhongChieu
		{
			get
			{
				return this._PhongChieu.Entity;
			}
			set
			{
				PhongChieu previousValue = this._PhongChieu.Entity;
				if (((previousValue != value) 
							|| (this._PhongChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongChieu.Entity = null;
						previousValue.CaiDatSuatChieus.Remove(this);
					}
					this._PhongChieu.Entity = value;
					if ((value != null))
					{
						value.CaiDatSuatChieus.Add(this);
						this._MaPhongChieu = value.MaPhongChieu;
					}
					else
					{
						this._MaPhongChieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhongChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SuatChieus(SuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.CaiDatSuatChieu = this;
		}
		
		private void detach_SuatChieus(SuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.CaiDatSuatChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ghe")]
	public partial class Ghe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGhe;
		
		private System.Nullable<int> _MaSoGhe;
		
		private string _DayGhe;
		
		private System.Nullable<int> _MaPhongChieu;
		
		private EntitySet<CaiDatGhe> _CaiDatGhes;
		
		private EntityRef<PhongChieu> _PhongChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGheChanging(int value);
    partial void OnMaGheChanged();
    partial void OnMaSoGheChanging(System.Nullable<int> value);
    partial void OnMaSoGheChanged();
    partial void OnDayGheChanging(string value);
    partial void OnDayGheChanged();
    partial void OnMaPhongChieuChanging(System.Nullable<int> value);
    partial void OnMaPhongChieuChanged();
    #endregion
		
		public Ghe()
		{
			this._CaiDatGhes = new EntitySet<CaiDatGhe>(new Action<CaiDatGhe>(this.attach_CaiDatGhes), new Action<CaiDatGhe>(this.detach_CaiDatGhes));
			this._PhongChieu = default(EntityRef<PhongChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGhe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGhe
		{
			get
			{
				return this._MaGhe;
			}
			set
			{
				if ((this._MaGhe != value))
				{
					this.OnMaGheChanging(value);
					this.SendPropertyChanging();
					this._MaGhe = value;
					this.SendPropertyChanged("MaGhe");
					this.OnMaGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoGhe", DbType="Int")]
		public System.Nullable<int> MaSoGhe
		{
			get
			{
				return this._MaSoGhe;
			}
			set
			{
				if ((this._MaSoGhe != value))
				{
					this.OnMaSoGheChanging(value);
					this.SendPropertyChanging();
					this._MaSoGhe = value;
					this.SendPropertyChanged("MaSoGhe");
					this.OnMaSoGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayGhe", DbType="VarChar(1)")]
		public string DayGhe
		{
			get
			{
				return this._DayGhe;
			}
			set
			{
				if ((this._DayGhe != value))
				{
					this.OnDayGheChanging(value);
					this.SendPropertyChanging();
					this._DayGhe = value;
					this.SendPropertyChanged("DayGhe");
					this.OnDayGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongChieu", DbType="Int")]
		public System.Nullable<int> MaPhongChieu
		{
			get
			{
				return this._MaPhongChieu;
			}
			set
			{
				if ((this._MaPhongChieu != value))
				{
					if (this._PhongChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhongChieu = value;
					this.SendPropertyChanged("MaPhongChieu");
					this.OnMaPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_CaiDatGhe", Storage="_CaiDatGhes", ThisKey="MaGhe", OtherKey="MaGhe")]
		public EntitySet<CaiDatGhe> CaiDatGhes
		{
			get
			{
				return this._CaiDatGhes;
			}
			set
			{
				this._CaiDatGhes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_Ghe", Storage="_PhongChieu", ThisKey="MaPhongChieu", OtherKey="MaPhongChieu", IsForeignKey=true)]
		public PhongChieu PhongChieu
		{
			get
			{
				return this._PhongChieu.Entity;
			}
			set
			{
				PhongChieu previousValue = this._PhongChieu.Entity;
				if (((previousValue != value) 
							|| (this._PhongChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongChieu.Entity = null;
						previousValue.Ghes.Remove(this);
					}
					this._PhongChieu.Entity = value;
					if ((value != null))
					{
						value.Ghes.Add(this);
						this._MaPhongChieu = value.MaPhongChieu;
					}
					else
					{
						this._MaPhongChieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhongChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CaiDatGhes(CaiDatGhe entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = this;
		}
		
		private void detach_CaiDatGhes(CaiDatGhe entity)
		{
			this.SendPropertyChanging();
			entity.Ghe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaiDatGhe")]
	public partial class CaiDatGhe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGhe;
		
		private int _MaSuatChieu;
		
		private System.Nullable<bool> _TrangThai;
		
		private EntityRef<Ghe> _Ghe;
		
		private EntityRef<SuatChieu> _SuatChieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGheChanging(int value);
    partial void OnMaGheChanged();
    partial void OnMaSuatChieuChanging(int value);
    partial void OnMaSuatChieuChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public CaiDatGhe()
		{
			this._Ghe = default(EntityRef<Ghe>);
			this._SuatChieu = default(EntityRef<SuatChieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGhe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaGhe
		{
			get
			{
				return this._MaGhe;
			}
			set
			{
				if ((this._MaGhe != value))
				{
					if (this._Ghe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGheChanging(value);
					this.SendPropertyChanging();
					this._MaGhe = value;
					this.SendPropertyChanged("MaGhe");
					this.OnMaGheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSuatChieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSuatChieu
		{
			get
			{
				return this._MaSuatChieu;
			}
			set
			{
				if ((this._MaSuatChieu != value))
				{
					if (this._SuatChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSuatChieuChanging(value);
					this.SendPropertyChanging();
					this._MaSuatChieu = value;
					this.SendPropertyChanged("MaSuatChieu");
					this.OnMaSuatChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ghe_CaiDatGhe", Storage="_Ghe", ThisKey="MaGhe", OtherKey="MaGhe", IsForeignKey=true)]
		public Ghe Ghe
		{
			get
			{
				return this._Ghe.Entity;
			}
			set
			{
				Ghe previousValue = this._Ghe.Entity;
				if (((previousValue != value) 
							|| (this._Ghe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ghe.Entity = null;
						previousValue.CaiDatGhes.Remove(this);
					}
					this._Ghe.Entity = value;
					if ((value != null))
					{
						value.CaiDatGhes.Add(this);
						this._MaGhe = value.MaGhe;
					}
					else
					{
						this._MaGhe = default(int);
					}
					this.SendPropertyChanged("Ghe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuatChieu_CaiDatGhe", Storage="_SuatChieu", ThisKey="MaSuatChieu", OtherKey="MaSuatChieu", IsForeignKey=true)]
		public SuatChieu SuatChieu
		{
			get
			{
				return this._SuatChieu.Entity;
			}
			set
			{
				SuatChieu previousValue = this._SuatChieu.Entity;
				if (((previousValue != value) 
							|| (this._SuatChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SuatChieu.Entity = null;
						previousValue.CaiDatGhes.Remove(this);
					}
					this._SuatChieu.Entity = value;
					if ((value != null))
					{
						value.CaiDatGhes.Add(this);
						this._MaSuatChieu = value.MaSuatChieu;
					}
					else
					{
						this._MaSuatChieu = default(int);
					}
					this.SendPropertyChanged("SuatChieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongChieu")]
	public partial class PhongChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhongChieu;
		
		private string _TenPhongChieu;
		
		private System.Nullable<int> _SoLuongGheNgoi;
		
		private EntitySet<CaiDatSuatChieu> _CaiDatSuatChieus;
		
		private EntitySet<Ghe> _Ghes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChieuChanging(int value);
    partial void OnMaPhongChieuChanged();
    partial void OnTenPhongChieuChanging(string value);
    partial void OnTenPhongChieuChanged();
    partial void OnSoLuongGheNgoiChanging(System.Nullable<int> value);
    partial void OnSoLuongGheNgoiChanged();
    #endregion
		
		public PhongChieu()
		{
			this._CaiDatSuatChieus = new EntitySet<CaiDatSuatChieu>(new Action<CaiDatSuatChieu>(this.attach_CaiDatSuatChieus), new Action<CaiDatSuatChieu>(this.detach_CaiDatSuatChieus));
			this._Ghes = new EntitySet<Ghe>(new Action<Ghe>(this.attach_Ghes), new Action<Ghe>(this.detach_Ghes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongChieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhongChieu
		{
			get
			{
				return this._MaPhongChieu;
			}
			set
			{
				if ((this._MaPhongChieu != value))
				{
					this.OnMaPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhongChieu = value;
					this.SendPropertyChanged("MaPhongChieu");
					this.OnMaPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongChieu", DbType="NVarChar(255)")]
		public string TenPhongChieu
		{
			get
			{
				return this._TenPhongChieu;
			}
			set
			{
				if ((this._TenPhongChieu != value))
				{
					this.OnTenPhongChieuChanging(value);
					this.SendPropertyChanging();
					this._TenPhongChieu = value;
					this.SendPropertyChanged("TenPhongChieu");
					this.OnTenPhongChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongGheNgoi", DbType="Int")]
		public System.Nullable<int> SoLuongGheNgoi
		{
			get
			{
				return this._SoLuongGheNgoi;
			}
			set
			{
				if ((this._SoLuongGheNgoi != value))
				{
					this.OnSoLuongGheNgoiChanging(value);
					this.SendPropertyChanging();
					this._SoLuongGheNgoi = value;
					this.SendPropertyChanged("SoLuongGheNgoi");
					this.OnSoLuongGheNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_CaiDatSuatChieu", Storage="_CaiDatSuatChieus", ThisKey="MaPhongChieu", OtherKey="MaPhongChieu")]
		public EntitySet<CaiDatSuatChieu> CaiDatSuatChieus
		{
			get
			{
				return this._CaiDatSuatChieus;
			}
			set
			{
				this._CaiDatSuatChieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongChieu_Ghe", Storage="_Ghes", ThisKey="MaPhongChieu", OtherKey="MaPhongChieu")]
		public EntitySet<Ghe> Ghes
		{
			get
			{
				return this._Ghes;
			}
			set
			{
				this._Ghes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CaiDatSuatChieus(CaiDatSuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = this;
		}
		
		private void detach_CaiDatSuatChieus(CaiDatSuatChieu entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = null;
		}
		
		private void attach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = this;
		}
		
		private void detach_Ghes(Ghe entity)
		{
			this.SendPropertyChanging();
			entity.PhongChieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVuNhanVien")]
	public partial class ChucVuNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChucVu;
		
		private string _TenChucVu;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChucVuChanging(int value);
    partial void OnMaChucVuChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    #endregion
		
		public ChucVuNhanVien()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(255)")]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVuNhanVien_NhanVien", Storage="_NhanViens", ThisKey="MaChucVu", OtherKey="MaChucVu")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVuNhanVien = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVuNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _Ten;
		
		private string _TenTaiKhoan;
		
		private string _MatKhau;
		
		private string _SoDienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<int> _MaChucVu;
		
		private System.Nullable<bool> _DaXoa;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _NgayVaoLam;
		
		private EntityRef<ChucVuNhanVien> _ChucVuNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnTenTaiKhoanChanging(string value);
    partial void OnTenTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnMaChucVuChanging(System.Nullable<int> value);
    partial void OnMaChucVuChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgayVaoLamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoLamChanged();
    #endregion
		
		public NhanVien()
		{
			this._ChucVuNhanVien = default(EntityRef<ChucVuNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(255)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiKhoan", DbType="VarChar(255)")]
		public string TenTaiKhoan
		{
			get
			{
				return this._TenTaiKhoan;
			}
			set
			{
				if ((this._TenTaiKhoan != value))
				{
					this.OnTenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TenTaiKhoan = value;
					this.SendPropertyChanged("TenTaiKhoan");
					this.OnTenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(255)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", DbType="Int")]
		public System.Nullable<int> MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					if (this._ChucVuNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoLam", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVaoLam
		{
			get
			{
				return this._NgayVaoLam;
			}
			set
			{
				if ((this._NgayVaoLam != value))
				{
					this.OnNgayVaoLamChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoLam = value;
					this.SendPropertyChanged("NgayVaoLam");
					this.OnNgayVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVuNhanVien_NhanVien", Storage="_ChucVuNhanVien", ThisKey="MaChucVu", OtherKey="MaChucVu", IsForeignKey=true)]
		public ChucVuNhanVien ChucVuNhanVien
		{
			get
			{
				return this._ChucVuNhanVien.Entity;
			}
			set
			{
				ChucVuNhanVien previousValue = this._ChucVuNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._ChucVuNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVuNhanVien.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._ChucVuNhanVien.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._MaChucVu = value.MaChucVu;
					}
					else
					{
						this._MaChucVu = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChucVuNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _Ten;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private System.Nullable<bool> _DaXoa;
		
		private System.Nullable<System.DateTime> _ThoiGianTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    partial void OnThoiGianTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianTaoChanged();
    #endregion
		
		public KhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianTao
		{
			get
			{
				return this._ThoiGianTao;
			}
			set
			{
				if ((this._ThoiGianTao != value))
				{
					this.OnThoiGianTaoChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTao = value;
					this.SendPropertyChanged("ThoiGianTao");
					this.OnThoiGianTaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuatChieu")]
	public partial class SuatChieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSuatChieu;
		
		private System.Nullable<int> _MaCaiDatSuatChieu;
		
		private System.Nullable<int> _MaPhim;
		
		private System.Nullable<decimal> _GiaVe;
		
		private System.Nullable<System.TimeSpan> _ThoiGianBatDau;
		
		private EntitySet<CaiDatGhe> _CaiDatGhes;
		
		private EntityRef<CaiDatSuatChieu> _CaiDatSuatChieu;
		
		private EntityRef<Phim> _Phim;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSuatChieuChanging(int value);
    partial void OnMaSuatChieuChanged();
    partial void OnMaCaiDatSuatChieuChanging(System.Nullable<int> value);
    partial void OnMaCaiDatSuatChieuChanged();
    partial void OnMaPhimChanging(System.Nullable<int> value);
    partial void OnMaPhimChanged();
    partial void OnGiaVeChanging(System.Nullable<decimal> value);
    partial void OnGiaVeChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiGianBatDauChanged();
    #endregion
		
		public SuatChieu()
		{
			this._CaiDatGhes = new EntitySet<CaiDatGhe>(new Action<CaiDatGhe>(this.attach_CaiDatGhes), new Action<CaiDatGhe>(this.detach_CaiDatGhes));
			this._CaiDatSuatChieu = default(EntityRef<CaiDatSuatChieu>);
			this._Phim = default(EntityRef<Phim>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSuatChieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSuatChieu
		{
			get
			{
				return this._MaSuatChieu;
			}
			set
			{
				if ((this._MaSuatChieu != value))
				{
					this.OnMaSuatChieuChanging(value);
					this.SendPropertyChanging();
					this._MaSuatChieu = value;
					this.SendPropertyChanged("MaSuatChieu");
					this.OnMaSuatChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCaiDatSuatChieu", DbType="Int")]
		public System.Nullable<int> MaCaiDatSuatChieu
		{
			get
			{
				return this._MaCaiDatSuatChieu;
			}
			set
			{
				if ((this._MaCaiDatSuatChieu != value))
				{
					if (this._CaiDatSuatChieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCaiDatSuatChieuChanging(value);
					this.SendPropertyChanging();
					this._MaCaiDatSuatChieu = value;
					this.SendPropertyChanged("MaCaiDatSuatChieu");
					this.OnMaCaiDatSuatChieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhim", DbType="Int")]
		public System.Nullable<int> MaPhim
		{
			get
			{
				return this._MaPhim;
			}
			set
			{
				if ((this._MaPhim != value))
				{
					if (this._Phim.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhimChanging(value);
					this.SendPropertyChanging();
					this._MaPhim = value;
					this.SendPropertyChanged("MaPhim");
					this.OnMaPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SuatChieu_CaiDatGhe", Storage="_CaiDatGhes", ThisKey="MaSuatChieu", OtherKey="MaSuatChieu")]
		public EntitySet<CaiDatGhe> CaiDatGhes
		{
			get
			{
				return this._CaiDatGhes;
			}
			set
			{
				this._CaiDatGhes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaiDatSuatChieu_SuatChieu", Storage="_CaiDatSuatChieu", ThisKey="MaCaiDatSuatChieu", OtherKey="MaCaiDatSuatChieu", IsForeignKey=true)]
		public CaiDatSuatChieu CaiDatSuatChieu
		{
			get
			{
				return this._CaiDatSuatChieu.Entity;
			}
			set
			{
				CaiDatSuatChieu previousValue = this._CaiDatSuatChieu.Entity;
				if (((previousValue != value) 
							|| (this._CaiDatSuatChieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CaiDatSuatChieu.Entity = null;
						previousValue.SuatChieus.Remove(this);
					}
					this._CaiDatSuatChieu.Entity = value;
					if ((value != null))
					{
						value.SuatChieus.Add(this);
						this._MaCaiDatSuatChieu = value.MaCaiDatSuatChieu;
					}
					else
					{
						this._MaCaiDatSuatChieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("CaiDatSuatChieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phim_SuatChieu", Storage="_Phim", ThisKey="MaPhim", OtherKey="MaPhim", IsForeignKey=true)]
		public Phim Phim
		{
			get
			{
				return this._Phim.Entity;
			}
			set
			{
				Phim previousValue = this._Phim.Entity;
				if (((previousValue != value) 
							|| (this._Phim.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phim.Entity = null;
						previousValue.SuatChieus.Remove(this);
					}
					this._Phim.Entity = value;
					if ((value != null))
					{
						value.SuatChieus.Add(this);
						this._MaPhim = value.MaPhim;
					}
					else
					{
						this._MaPhim = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phim");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CaiDatGhes(CaiDatGhe entity)
		{
			this.SendPropertyChanging();
			entity.SuatChieu = this;
		}
		
		private void detach_CaiDatGhes(CaiDatGhe entity)
		{
			this.SendPropertyChanging();
			entity.SuatChieu = null;
		}
	}
}
#pragma warning restore 1591
